sudo: required
services:
  - docker

before_install:
  - docker build -t harriswong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harriswong/react-test npm test

after_success:
  - docker build -t harriswong25/multi-client ./client
  - docker build -t harriswong25/multi-nginx ./nginx
  - docker build -t harriswong25/multi-server ./server
  - docker build -t harriswong25/multi-worker ./worker

  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push harriswong25/multi-client
  - docker push harriswong25/multi-nginx
  - docker push harriswong25/multi-server
  - docker push harriswong25/multi-worker
